### Create Unipile Hosted Auth Link
POST https://jpfxxoflclkpqsibvdil.supabase.co/functions/v1/unipile/accounts/link
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ2NGVkNTJjLTE1MmMtNDYwZC04NTlhLWI1MzYyY2E5MzU0NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2pwZnh4b2ZsY2xrcHFzaWJ2ZGlsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJiYWRjZWEzOC1mYmIyLTQ1Y2YtOTMxNC04ODc3MWI2M2Y0MmQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc3MTI1MjA3LCJpYXQiOjE3NzcxMjE2MDcsImVtYWlsIjoiZmNvc3RhY2hhdmVzQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJmY29zdGFjaGF2ZXNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiYmFkY2VhMzgtZmJiMi00NWNmLTkzMTQtODg3NzFiNjNmNDJkIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzcxMTUxNjF9XSwic2Vzc2lvbl9pZCI6Ijc2NTVjMDc5LTIyMDgtNGNmOC04Mjg5LTQzODk3NzgxNDFkZiIsImlzX2Fub255bW91cyI6ZmFsc2V9.klL4lZR2KfbfjYCHr9bUTIuVw9EouObPhrQgVM3MYwSB1e2dVOE_SRfDH2rZ48XzmCeD5R0ra-nk5yPWhFSeBw

{
  "success_redirect_url": "http://localhost:3000",
  "userId": "badcea38-fbb2-45cf-9314-88771b63f42d"
}

### Busca usuário autenticado
GET https://jpfxxoflclkpqsibvdil.supabase.co/auth/v1/user
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ2NGVkNTJjLTE1MmMtNDYwZC04NTlhLWI1MzYyY2E5MzU0NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2pwZnh4b2ZsY2xrcHFzaWJ2ZGlsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJiYWRjZWEzOC1mYmIyLTQ1Y2YtOTMxNC04ODc3MWI2M2Y0MmQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc3MTI1MjA3LCJpYXQiOjE3NzcxMjE2MDcsImVtYWlsIjoiZmNvc3RhY2hhdmVzQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJmY29zdGFjaGF2ZXNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiYmFkY2VhMzgtZmJiMi00NWNmLTkzMTQtODg3NzFiNjNmNDJkIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzcxMTUxNjF9XSwic2Vzc2lvbl9pZCI6Ijc2NTVjMDc5LTIyMDgtNGNmOC04Mjg5LTQzODk3NzgxNDFkZiIsImlzX2Fub255bW91cyI6ZmFsc2V9.klL4lZR2KfbfjYCHr9bUTIuVw9EouObPhrQgVM3MYwSB1e2dVOE_SRfDH2rZ48XzmCeD5R0ra-nk5yPWhFSeBw

### Test unipile webhook (header)
POST https://jpfxxoflclkpqsibvdil.supabase.co/functions/v1/unipile-webhook
Content-Type: application/json
x-unipile-webhook-secret: f3c9b4e2a1d7c0f8e4b19a7c55d2e0f3c8a4d1b7e6f29c0db3a7f4e1c2b8d6f0

{
  "status":"CREATION_SUCCESS",
  "account_id": "HZ5ydcdSTAiVWl8UrV11VA",
  "name": "badcea38-fbb2-45cf-9314-88771b63f42d"
}
### // "status":"CREATION_SUCCESS", or "RECONNECTED" for reconnect type